spring:
  datasource:
    name : druidDataSource
    url : jdbc:mysql://192.168.151.22:3306/crawler?useUnicode=true&characterEncoding=UTF-8
    username : crawler
    password : 123456
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.jdbc.Driver
    filters : stat
    maxActive : 60
    initialSize : 10
    maxWait : 60000
    minIdle : 1
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : false
    maxOpenPreparedStatements : 20

